Fix install issue due to drollup
The `@next` version of https://github.com/cmorten/deno-rollup does not provide any package when creating a new Snel project, resulting in the error

>error: Module not found "https://denopkg.com/buttercubz/deno-rollup@next/plugins/terser/mod.ts".
>    at https://deno.land/x/snel@v0.7.1/src/shared/internal_plugins.ts:13:24

This _should_ hopefully fix the issue